### ISSUE TITLE
Please update podspec

### ISSUE THREAD

**Issue by MattKiazyk** [victorBaro/VBFPopFlatButton#23]
Podspec references 0.0.5 tag. Latest changes are not tagged.

**Comment by yannickl** [comment]
When do you plan to push the `0.0.6` to the trunk repo?

**Comment by victorBaro** [comment]
Thanks for your comment @yannickl 
Did everything apart from pushing it to trunk.... My mistake.
Just pushed it.

**Comment by yannickl** [comment]
@victorBaro Perfect, thank you!

By the way, the project is really great. :+1:
