### ISSUE TITLE
Is this library still being developed?

### ISSUE THREAD

**Issue by prscX** [victorBaro/VBFPopFlatButton#39]
Hi @victorBaro ,

First of all I would like to appreciate for creating such a cool animation buttons

I want to know is this library still in active development? I am planning to write a ReactNative wrapper around the same

Thanks
Pranav

**Comment by victorBaro** [comment]
Hello @prscX 
I haven't updated it for a while, just fixing minor bugs. My idea is to rewrite it in swift in the near future, maintaining the same public API. Glad to hear you are going to write a wrapper in react native, please let me know when you do, or feel free to submit a PR updating the readme mentioning your new library in it.

**Comment by prscX** [comment]
Good to hear @victorBaro about plans to rewrite this library using Swift

Soon I am planning to write a RN wrapper, I will definitely keep you in the loop and will raise a PR for the reference

Thanks
Pranav

**Comment by prscX** [comment]
Hi @victorBaro,

I am starting to build RN bridge for this library. Do you know any similar library for Android platform as well, I have searched a lot but could not find one.

Thanks
Pranav

**Comment by victorBaro** [comment]
@prscX I have not come across anything similar on android.
