### ISSUE TITLE
Broken link to animated image

### ISSUE THREAD

**Issue by Noitidart** [victorBaro/VBFPopFlatButton#41]
Hi there,

In readme, the link https://camo.githubusercontent.com/b18993cbfe91de8abdc0019dc9a6cd44707eec21/68747470733a2f2f6431337961637572716a676172612e636c6f756466726f6e742e6e65742f75736572732f3338313133332f73637265656e73686f74732f313639363538302f766266706f70666c6174627574746f6e332e676966 is a broken link. It says it's supposed to give us the animated prview.

**Comment by victorBaro** [comment]
Oops, thank you for letting me know.

This is the preview: ![](https://cdn.dribbble.com/users/381133/screenshots/1696580/vbfpopflatbutton3.gif) 

I am going to update the readme. Thanks!
